#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "fec3b39b059c0f88fa6b20f5ed012b1aa203a8b4"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  version = "1.3.1"

[[constraint]]
  name = "github.com/golang/groupcache"
  branch = "master"

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  name = "github.com/miekg/pkcs11"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"
